### ISSUE TITLE
Dies with NPE on selecting a repo with no description

### ISSUE THREAD

**Issue by bammellab** [yodle/android-kotlin-demo#19]
Found a little NPE problem - when selecting a repo with no description.  For example, most of the time the "Yalantis/JellyToolbar" repo comes up on the 1st search page (but not always).   This repo has no description and selecting it for the detail view throws an exception.   I fixed this by simply adding the ? to the description as shown below:

    data class Repository(
        val id: Long,
        val name: String,
        val full_name: String,
        val owner: RepositoryOwner,
        val html_url: String,
        val description: String?,

Thank you for sharing your project!

**Comment by dsn5ft** [comment]
@kotlin-candy good catch! addressed in #20
